# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test structural properties search scripts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test salt bridges 
      shell: bash
      run: python3 salt_bridges.py -f test_data/gb1.pdb
    - name: Test hydrogen bonds 
      shell: bash
      run: python3 h_bond_test.py -f test_data/gb1.pdb
    - name: Test hydrophobic cluster 
      shell: bash
      run: python3 hydrophobic_cluster.py -f test_data/gb1.pdb
    - name: Test surface amino acids 
      shell: bash
      run: python3 surface.py -f test_data/gb1.pdb -c test_data/surface.csv
      
